In [1]:
import pandas as pd
from typing import Dict
from datetime import datetime
from enum import Enum
import numpy as np

In [1]:
exp_name = "D2024-04-18_15:54:02_R1_W8"
file_loc = "../../data/{f}/worker_transition.csv".format(f=exp_name)

In [3]:
dat = pd.read_csv(file_loc)

In [4]:
dat.head()

,Unnamed: 0,key,start,finish,called_from,time
0,0,('block-info-_map_read_frame-c50155175b03e4c1e...,released,waiting,tcp://10.201.0.212:34699,1.713456e+09
1,1,('block-info-_map_read_frame-c50155175b03e4c1e...,waiting,ready,tcp://10.201.0.212:34699,1.713456e+09
2,2,('block-info-_map_read_frame-c50155175b03e4c1e...,ready,executing,tcp://10.201.0.212:34699,1.713456e+09
3,3,"('array-8838909ee9756e34565341881e2e6f0c', 125)",released,waiting,tcp://10.201.0.212:38553,1.713456e+09
4,4,('block-info-_map_read_frame-c50155175b03e4c1e...,released,waiting,tcp://10.201.0.212:38577,1.713456e+09

In [14]:
dat.loc[(dat["finish"] == "flight") | (dat["start"] == "flight")]

,Unnamed: 0,key,start,finish,called_from,time
339,339,"('array-8838909ee9756e34565341881e2e6f0c', 123)",fetch,flight,tcp://10.201.0.212:34699,1.713456e+09
342,342,"('array-8838909ee9756e34565341881e2e6f0c', 120)",fetch,flight,tcp://10.201.0.212:38577,1.713456e+09
419,419,('block-info-_map_read_frame-c50155175b03e4c1e...,fetch,flight,tcp://10.201.0.212:45449,1.713456e+09
420,420,('block-info-_map_read_frame-c50155175b03e4c1e...,fetch,flight,tcp://10.201.0.212:38553,1.713456e+09
441,441,"('array-8838909ee9756e34565341881e2e6f0c', 120)",flight,memory,tcp://10.201.0.212:38577,1.713456e+09
...,...,...,...,...,...,...
64832,64832,"('stack-b4b92b70b53be1d3b50e36696c31dac6', 75,...",flight,memory,tcp://10.201.0.229:37485,1.713456e+09
64844,64844,"('stack-b4b92b70b53be1d3b50e36696c31dac6', 39,...",fetch,flight,tcp://10.201.0.229:37485,1.713456e+09
64888,64888,"('stack-b4b92b70b53be1d3b50e36696c31dac6', 39,...",flight,memory,tcp://10.201.0.229:37485,1.713456e+09
64906,64906,('block-info-save_file-3bc2c82f3124827ed7e7612...,flight,memory,tcp://10.201.0.229:44955,1.713456e+09
64918,64918,"('stack-b4b92b70b53be1d3b50e36696c31dac6', 62,...",flight,memory,tcp://10.201.0.212:38577,1.713456e+09